version: "3.3"

services:
  backend:
    image: jeffery426/plagiarismDetector_backend:latest # âœ… ç›´æ¥å¾ Docker Hub æ‹‰å–
    container_name: django-backend
    restart: always
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      # - SECRET_KEY=${SECRET_KEY}
      # - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      # - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      # - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      # - DB_NAME=${DB_NAME}
      # - DB_USER=${DB_USER}
      # - DB_PASSWORD=${DB_PASSWORD}
      # - DB_HOST=${DB_HOST}
      # - DB_PORT=${DB_PORT}
    depends_on: [] # ğŸ”¹ å› ç‚º MySQL åœ¨å¤–éƒ¨ï¼Œæ‰€ä»¥ä¸å†ä¾è³´ `db`
    env_file:
      - .env

  frontend:
    image: jeffery426/plagiarismDetector_frontend:latest # âœ… ç›´æ¥å¾ Docker Hub æ‹‰å–
    container_name: react-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    volumes:
      - static_volume:/usr/share/nginx/html/static
    env_file:
      - .env

volumes:
  static_volume:
