name: test1
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py313h06a4308_0
  - python=3.13.1=hf623796_100_cp313
  - python_abi=3.13=0_cp313
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py313h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py313h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - asgiref==3.8.1
      - attrs==25.3.0
      - backoff==2.2.1
      - bcrypt==4.3.0
      - bitsandbytes==0.45.5
      - blinker==1.9.0
      - build==1.2.2.post1
      - cachetools==5.5.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.1
      - chroma-hnswlib==0.7.6
      - chromadb==1.0.7
      - click==8.1.8
      - coloredlogs==15.0.1
      - dataclasses-json==0.6.7
      - deprecated==1.2.18
      - distro==1.9.0
      - durationpy==0.9
      - faiss-cpu==1.11.0
      - fastapi==0.115.9
      - filelock==3.18.0
      - flask==3.1.0
      - flask-cors==5.0.1
      - flatbuffers==25.2.10
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.0rc0
      - google-api-python-client==2.169.0
      - google-auth==2.39.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - greenlet==3.2.1
      - grpcio==1.71.0
      - grpcio-status==1.71.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.30.2
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - jieba==0.42.1
      - jinja2==3.1.6
      - jiter==0.9.0
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - kubernetes==32.0.1
      - langchain==0.3.24
      - langchain-community==0.3.23
      - langchain-core==0.3.56
      - langchain-huggingface==0.1.2
      - langchain-text-splitters==0.3.8
      - langgraph==0.4.3
      - langgraph-checkpoint==2.0.25
      - langgraph-prebuilt==0.1.8
      - langgraph-sdk==0.1.69
      - langsmith==0.3.38
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - mmh3==5.1.0
      - mpmath==1.3.0
      - multidict==6.4.3
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==2.2.5
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - oauthlib==3.2.2
      - onnxruntime==1.21.1
      - openai==1.76.2
      - opencc-python-reimplemented==0.1.7
      - opentelemetry-api==1.32.1
      - opentelemetry-exporter-otlp-proto-common==1.32.1
      - opentelemetry-exporter-otlp-proto-grpc==1.32.1
      - opentelemetry-instrumentation==0.53b1
      - opentelemetry-instrumentation-asgi==0.53b1
      - opentelemetry-instrumentation-fastapi==0.53b1
      - opentelemetry-proto==1.32.1
      - opentelemetry-sdk==1.32.1
      - opentelemetry-semantic-conventions==0.53b1
      - opentelemetry-util-http==0.53b1
      - orjson==3.10.18
      - ormsgpack==1.9.1
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.2.1
      - posthog==4.0.1
      - propcache==0.3.1
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - psutil==7.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydantic-settings==2.9.1
      - pygments==2.19.1
      - pymupdf==1.25.5
      - pyparsing==3.2.3
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.0.0
      - rpds-py==0.24.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentence-transformers==4.1.0
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.40
      - starlette==0.45.3
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - torch==2.7.0
      - tqdm==4.67.1
      - transformers==4.51.3
      - triton==3.3.0
      - typer==0.15.3
      - typing-extensions==4.13.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - uritemplate==4.1.1
      - urllib3==2.4.0
      - uvicorn==0.34.2
      - uvloop==0.21.0
      - watchfiles==1.0.5
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.20.0
      - zipp==3.21.0
      - zstandard==0.23.0
prefix: /home/undergrad/miniconda3/envs/test1
